## Tensors Examples

In [1]:
import torch

a = torch.tensor(1.)
print(a)

tensor(1.)


In [2]:
b = 1.
print(b)

1.0


In [3]:
print(a.shape)

torch.Size([])


## Rank 1 Tensor, Vectors

In [4]:
b = [1., 2., 3.]
print(b)

[1.0, 2.0, 3.0]


In [5]:
a = torch.tensor([1., 2., 3.])
print(a)

tensor([1., 2., 3.])


In [6]:
print(a.shape)

torch.Size([3])


In [7]:
print(a.size)

<built-in method size of Tensor object at 0x1379e1270>


## Rank 2 Tensor, Matrix

In [8]:
a = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
print(a.shape)

torch.Size([2, 3])


In [10]:
a.shape

torch.Size([2, 3])

In [12]:
a.dim

<function Tensor.dim()>

## 3D Tensor

In [13]:
a = torch.tensor([[[1., 2., 3.],
                   [4., 5., 6.]],
                  [[7., 8., 9.],
                   [10., 11., 12.]]])
print(a)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [14]:
a.shape

torch.Size([2, 2, 3])

## 4D Tensor

In [15]:
a = torch.tensor([[[[1., 2., 3.],
                   [4., 5., 6.]],
                  [[7., 8., 9.],
                   [10., 11., 12.]]],
                  [[[13., 14., 15.],
                   [16., 17., 28.]],
                  [[19., 20., 21.],
                   [22., 23., 24.]]]])
print(a)

tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],

         [[ 7.,  8.,  9.],
          [10., 11., 12.]]],


        [[[13., 14., 15.],
          [16., 17., 28.]],

         [[19., 20., 21.],
          [22., 23., 24.]]]])


In [16]:
a.shape

torch.Size([2, 2, 2, 3])

# Useful Tensor Functions

## 1) Creating a tensor

In [17]:
t = torch.tensor([[1., 2., 3.], [4., 5., 6.]])

## 2) Check the shape

In [18]:
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [19]:
print(t.shape)

torch.Size([2, 3])


## 3) Check the rank, or number of dimensions

In [20]:
print(t.ndim)

2


## 4) Check the data type

In [21]:
print(t.dtype)

torch.float32


In [22]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]]) 

In [23]:
print(a.dtype)

torch.int64


## 5) Convert numpy array to tensor

In [24]:
import numpy as np
np_array = np.array([1., 2., 3.])
t1 = torch.from_numpy(np_array)
t2 = torch.tensor(np_array)
# t and np_array share the same memory
print(np_array)
print(t1)
print(t2)

[1. 2. 3.]
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


In [ ]:
t1[2] = 10.

In [ ]:
print(t1)

In [ ]:
print(np_array)

In [ ]:
print(t2)

In [ ]:
t2[0] = 20.

In [ ]:
print(t2)

In [ ]:
print(t1)
print(np_array)

## 6) Change data type

In [ ]:
print(t1.dtype)

In [ ]:
t1 = t1.to(torch.float32)

In [ ]:
print(t1.dtype)

## 7) Check the device type

In [ ]:
t1.device

In [ ]:
torch.cuda.is_available()

## 8) Change tensor shape

In [ ]:
a = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(a)

In [ ]:
print(a.view(3,2))

In [ ]:
print(a.view(-1,2))

In [ ]:
print(a.view(3,-1))

## 9) Transpose a tensor

In [ ]:
a = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(a)

In [ ]:
print(a.T)

In [ ]:
b = torch.tensor([[[1., 2., 3.],
                  [4., 5., 6.]],
                  [[7., 8., 9.],
                   [10., 11., 12.]]])
print(b)

In [ ]:
print(b.mT)

## 10) Multiplying matrices

In [25]:
a = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
b = torch.tensor([[2., 3., 4.],
                  [5., 6., 7.],
                  [8., 9., 10]])

In [26]:
a.matmul(b.T)

tensor([[ 20.,  38.,  56.],
        [ 47.,  92., 137.]])

In [27]:
import torch
a = torch.tensor([[1.,2.], [3.,4.]])
b = torch.tensor([10.,20.])

In [28]:
a

tensor([[1., 2.],
        [3., 4.]])

In [29]:
b

tensor([10., 20.])

In [30]:
a+b

tensor([[11., 22.],
        [13., 24.]])